#!/bin/bash

pgrep bspwm || exit 1

# bspc config normal_border_color "#4a4a4a"
# bspc config focused_border_color "#f44242"
bspc config normal_border_color "#bababa"
bspc config focused_border_color "#d326ff"

bspc config border_width 	3
bspc config window_gap		12
bspc config -m ^1 top_padding 26
bspc config -m ^2 top_padding 0

bspc config click_to_focus any
#bspc config ignore_ewmh_focus true

bspc config split_ratio		0.5
bspc config focus_by_distance	true

bspc monitor ^1 -d I II III IV V VI
bspc monitor ^2 -d I II III IV V VI
#bspc monitor ^3 -d I II III IV V VI

bspc rule -a org-igoweb-cgoban-CGoban state=floating border=off
bspc rule -a gcolor2 state=floating center=on
bspc rule -a clone state=floating center=on
bspc rule -a Workrave sticky=on
bspc rule -a '*:zoom' state=floating # sticky=on
# Fixes buggy KDE panel dropdowns
# bspc rule -a plasmashell state=floating sticky=on manage=off border=off
# bspc rule -a krunner state=floating layer=above sticky=on border=off
# bspc rule -a Plasma state=floating manage=off layer=above
# bspc rule -a krunner state=floating border=off
# bspc rule -a plasmashell sticky=on layer=above state=floating manage=off
bspc rule -a plasmashell state=floating border=off layer=normal manage=off center=true
bspc rule -a krunner state=floating
bspc rule -a Plasma state=floating manage=off layer=above

(pgrep sxhkd || sxhkd) &

# Screen blanking handled by hardware motion detection.
#xset s 0 -dpms

#xinput set-prop 'Clearly Superior Technologies. CST Laser Trackball' "libinput Scroll Method Enabled" 0, 0, 1
#xinput set-prop 'Clearly Superior Technologies. CST Laser Trackball' "libinput Natural Scrolling Enabled" 1
